#pragma once

#include "resource.h"

#define IDD_MIDDLE_SET_BUTTON (WM_APP + 1)
#define IDD_RIGHT_SET_BUTTON (WM_APP + 2)
#define IDD_X1_SET_BUTTON (WM_APP + 3)
#define IDD_X2_SET_BUTTON (WM_APP + 4)
#define IDD_LR_SET_BUTTON (WM_APP + 5)
#define IDD_RL_SET_BUTTON (WM_APP + 6)
#define IDD_ML_SET_BUTTON (WM_APP + 7)
#define IDD_MR_SET_BUTTON (WM_APP + 8)

#define IDD_SET_OKBUTTON (WM_APP + 10)
#define IDD_SET_CANCELBUTTON (WM_APP + 11)
#define WM_TO_TRAY (WM_APP + 12)
#define IDD_STR_SET_COMBOBOX (WM_APP + 13)
#define IDD_CTRL_SET_COMBOBOX (WM_APP + 14)
#define IDD_ALT_SET_COMBOBOX (WM_APP + 15)
#define IDD_SHIFT_SET_COMBOBOX (WM_APP + 16)
